### ISSUE TITLE
upo_people_tracker   &  spencer_to_upo_people  

### ISSUE THREAD

**Issue by zltnl** [robotics-upo/pedlab#1]
Hello, I am very interested in your work. But I can't find upo_people_tracker and spencer_to_upo_people pkg！
 What should i do? Sincerely look forward to your answer.

**Comment by noeperez** [comment]
Hello,

sorry for the delay in the reply. 
Forget about the upo_people_tracker and spencer_to_upo_people, they are not required to run the simulator. We have also removed the dependences on the spencer_msgs. 

Please, clone the branch "develop" of this package, and install the dependencies indicated in the ROS dependencies section of the branch. 
To run an example of the simulator, just use the launch file corridors.launch. 

Best regards,
Noé

**Comment by zltnl** [comment]
OK，thanks！！！
